inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: #{File.read('.ruby-version').strip}

  Exclude:
    - log/**/*
    - poc/**/*
    - tmp/**/*
    - vendor/**/*
  Include:
    - ants.gemspec
    - exe/**/*
    - Gemfile
    - Guardfile
    - lib/**/*
    - Rakefile
    - spec/**/*

# Layout
Layout/LineLength:
  Max: 120

# Metrics
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 250

# RSpec
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleExpectations:
  Max: 10
RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - but
    - and
RSpec/DescribedClass:
  SkipBlocks: true
RSpec/MultipleMemoizedHelpers:
  Enabled : false
RSpec/NamedSubject:
  Enabled : false

# Style

Style/DateTime:
  Enabled: true
Style/NumericLiterals:
  Enabled: false
Style/CommentAnnotation:
  Enabled: true
  Keywords:
    - DEPRECATED
    - EPHEMERAL
    - FIXME
    - HACK
    - IMPORTANT
    - NOTE
    - OPTIMIZE
    - REMOVE_ME
    - REVIEW
    - SECURITY
    - TODO
    - WARNING
Style/Documentation:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '[]'
Style/RegexpLiteral:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
Style/SymbolArray:
  EnforcedStyle: percent
  MinSize: 4

