#!/usr/bin/env ruby

require 'date'
require 'debug'

require_relative '../lib/ants'

world = Ants::Worlds::Simulate.new
window = Ants::Helpers::Window.new(width: 640, height: 400, title: 'Ants!')

context = {
  done: false,
  width: window.width,
  height: window.height,
  window: # IMPROVE: put in context or Ants.window ?
}

Ants.world = world

colony = Ants::Entities::Colony.new({ position: { x: window.center[0], y: window.center[1] } })
ant = Ants::Entities::Ant.new({ position: { x: colony.position.x, y: colony.position.y } })

world.entities << colony
world.entities << ant

last = DateTime.now.strftime('%Q').to_i # rubocop:disable Style/DateTime

window.update do
  now = DateTime.now.strftime('%Q').to_i # rubocop:disable Style/DateTime
  # puts "last: #{last}, now: #{now}"

  context[:delta] = (now - last)

  # puts "delta: #{context[:delta]}"

  last = now

  world.tick(context)
end

window.show
