#!/usr/bin/env ruby

require 'date'
require 'debug'

require_relative '../lib/ants'

world = Ants::Worlds::Simulate.new

context = {
  done: false
}

Ants.world = world

colony = Ants::Entities::Colony.new({ position: { x: 0, y: 0 } })
ant = Ants::Entities::Ant.new({ position: { x: colony.position.x, y: colony.position.y } })

world.entities << colony
world.entities << ant

last = DateTime.now.strftime('%Q').to_i # rubocop:disable Style/DateTime

loop do
  now = DateTime.now.strftime('%Q').to_i # rubocop:disable Style/DateTime
  # puts "last: #{last}, now: #{now}"

  context[:delta] = (now - last)

  # puts "delta: #{context[:delta]}"

  last = now

  world.tick(context)

  sleep 0.01

  break if context[:done]
end
